//
// Generated file, do not edit! Created by nedtool 4.6 from m2.msg.
//

#ifndef _M2_M_H_
#define _M2_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>m2.msg:1</tt> by nedtool.
 * <pre>
 * message MessageNoeud
 * {
 *     int R;
 *     int T;
 *     int ID;
 * }
 * </pre>
 */
class MessageNoeud : public ::cMessage
{
  protected:
    int R_var;
    int T_var;
    int ID_var;

  private:
    void copy(const MessageNoeud& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MessageNoeud&);

  public:
    MessageNoeud(const char *name=NULL, int kind=0);
    MessageNoeud(const MessageNoeud& other);
    virtual ~MessageNoeud();
    MessageNoeud& operator=(const MessageNoeud& other);
    virtual MessageNoeud *dup() const {return new MessageNoeud(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getR() const;
    virtual void setR(int R);
    virtual int getT() const;
    virtual void setT(int T);
    virtual int getID() const;
    virtual void setID(int ID);
};

inline void doPacking(cCommBuffer *b, MessageNoeud& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MessageNoeud& obj) {obj.parsimUnpack(b);}


#endif // ifndef _M2_M_H_

